# Generated by Django 3.2.5 on 2021-07-04 12:38

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FilePathField(path=pathlib.PurePosixPath('/home/kalo/public_html/deploy/app/static/img')),
        ),
    ]
