#!/usr/bin/tcsh

cd $DEPLOY
pwd
head venv/bin/activate.csh
source venv/bin/activate.csh



#manage.py shell -c 'import script.roule'
#manage.py check --deploy
#manage.py makemigrations --dry-run
#manage.py check
